name: RentVsBuyNativeiPad
options:
  minimumXcodeGenVersion: 2.40.0
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: 2
    DEVELOPMENT_TEAM: ""
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UIRequiresFullScreen: YES
    SUPPORTS_MACCATALYST: NO
targets:
  RentVsBuyNativeiPad:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_NAME: RentVsBuyNativeiPad
        PRODUCT_BUNDLE_IDENTIFIER: com.derrickfox.rentvsbuynativeipad
